In [ ]:
# Regression
# Simple Linear Regression
# Multiple Linear Regression
# Polynomial Linear Regression

# Classification
# KNN
# Decision Tree
# Random Forest
# SVC

In [ ]:
import pandas as pd
df=pd.read_csv('fish.csv')

In [ ]:
df.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [ ]:
df.corr(numeric_only=True)

           Weight   Length1   Length2   Length3    Height     Width
Weight   1.000000  0.915712  0.918618  0.923044  0.724345  0.886507
Length1  0.915712  1.000000  0.999517  0.992031  0.625378  0.867050
Length2  0.918618  0.999517  1.000000  0.994103  0.640441  0.873547
Length3  0.923044  0.992031  0.994103  1.000000  0.703409  0.878520
Height   0.724345  0.625378  0.640441  0.703409  1.000000  0.792881
Width    0.886507  0.867050  0.873547  0.878520  0.792881  1.000000

In [ ]:
x=df[['Length3']]
y=df['Weight']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error ,mean_squared_error,r2_score
print(lr.coef_,lr.intercept_)
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

[28.32377215] -495.47986333546874
114.92552285193783
21835.271889248193
0.8464891636131896

In [ ]:
x=df.drop('Weight',axis=1)
y=df['Weight']
x=pd.get_dummies(x,drop_first=True)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import mean_absolute_error ,mean_squared_error,r2_score
print(lr.coef_,lr.intercept_)
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

[ -59.1395506    55.61529428   39.05378679  -10.73045193    7.22621264
  139.56242576   74.67079989 -331.37548435   34.99483542  330.68647533
   47.64152441] -826.8181491630844
65.30005153357352
7007.383189853791
0.9507352480054523

In [ ]:
x=df.drop('Weight',axis=1)
y=df['Weight']
x=pd.get_dummies(x,drop_first=True)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)


from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_train=poly.fit_transform(x_train)
x_test=poly.transform(x_test)



from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
from sklearn.metrics import mean_absolute_error ,mean_squared_error,r2_score
print(lr.coef_,lr.intercept_)
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

[ 1.00481997e-07  2.23471960e+02  3.24592202e+01 -2.90419079e+02
 -2.63384447e+02  7.02468434e+02 -4.80771345e+02 -6.45253719e+02
 -8.81097583e+02 -7.14682406e+02 -7.06503965e+02 -1.74047322e+02
  3.21078437e+01 -1.52826523e+02  6.20823894e+01 -9.35200670e+00
  1.24945012e+02 -1.66838381e+02  3.63930848e+00 -8.88939150e+01
 -9.18903561e+01 -9.23245813e+01  2.92902991e+02  1.18706622e+02
 -4.07709436e+01 -9.99057231e+01 -3.90803164e+01  1.33568991e+02
 -5.22025319e+02 -8.72958641e+02 -3.42886845e+02 -3.46580775e+02
  5.42184486e+01 -1.92714384e+01  1.15754255e+02 -9.24176060e+01
  3.58974567e+01  5.13996358e+02  9.54300772e+02  4.62247846e+02
  4.67085186e+02 -2.22831809e+02 -1.34537434e+01 -2.22363857e+01
  1.42521414e+02  2.21640598e+02  9.94526182e+01  4.66011593e+01
  1.20684176e+02 -1.61761410e+02  6.92499455e+01 -3.09045813e+02
 -5.27313288e+02 -4.70453117e+02 -4.06095236e+02 -5.68453401e+02
 -2.18563518e+02 -4.80771345e+02  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -6.45253719e+02
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -8.81097583e+02  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -7.14682406e+02  0.00000000e+00  0.00000000e+00 -7.06503965e+02
  0.00000000e+00 -1.74047322e+02] 1480.359944252754
54.36926141965788
7062.155832389015
0.9503501740659408